create table admission (
roll_no serial primary key,
name varchar,
college_name varchar,
qualification varchar,
is_fee_paid boolean default true
)

insert into admission (name,college_name,qualification,is_fee_paid) values
('akash','YCCE','HSC',true),
('ramesh','VNIT','HSC',true),
('suresh','RamdevBaba','HSC',true),
('ram','YCCE','Poly',true),
('laksham','Raisoni','HSC',true),
('sita','YCCE','HSC',false),
('gita','RamdevBaba','HSC',true),
('lina','Raisoni','Poly',true),
('rina','VNIT','HSC',true),
('nihal','RamdevBaba','Poly',null),
('ashwin','VNIT','HSC',true),
('renuka','YCCE','Poly',null),
('namrata','VNIT','HSC',true),
('vaishanavi','VNIT','Poly',true),
('pallavi','YCCE','HSC',true),
('krishna','Raisoni','HSC',true),
('sunil','RamdevBaba','Poly',true),
('rahul','YCCE','Poly',true),
('kuldip','Raisoni','HSC',true),
('anjali','VNIT','Poly',null),
('kunal','Raisoni','HSC',true),
('lakhan','RamdevBaba','HSC',false),
('runali','RamdevBaba','HSC',true),
('bharat','Raisoni','Poly',false),
('srivalli','Raisoni','HSC',true),
('pushpa','VNIT','HSC',true),
('shreyas','YCCE','Poly',true),
('yash','Raisoni','Poly',true),
('akshay','VNIT','HSC',true),
('disha','VNIT','HSC',false),
('alia','RamdevBaba','HSC',true),
('kareena','Raisoni','HSC',true),
('salman','VNIT','HSC',true),
('sharukh','YCCE','Poly',null),
('vicky','YCCE','HSC',false),
('ayushman','Raisoni','Poly',true),
('kartik','YCCE','Poly',true),
('pratik','RamdevBaba','Poly',null),
('rameshwar','VNIT','HSC',true),
('kamlesh','YCCE','HSC',true)

select * from admission