create table vehicle_survey (
surveyID serial primary key,
person_name varchar,
vehicle_category varchar,
number_of_vehicles int,
city varchar
)

insert into vehicle_survey (person_name,vehicle_category,number_of_vehicles,city) values
('Aarav Sharma', 'Car', 2, 'Mumbai'),
('Ananya Patel', 'Motorcycle', 1, 'Delhi'),
('Aryan Singh', 'Car', 1, 'Bengaluru'),
('Ishita Kumar', 'Scooter', 2, 'Chennai'),
('Vivaan Reddy', 'Car', 3, null),
('Siya Joshi', 'Motorcycle', 1, 'Kolkata'),
('Kabir Mehta', 'Car', 2, 'Pune'),
('Diya Desai', 'Scooter', 1, 'Jaipur'),
('Rohan Verma', 'Car', 1, 'Ahmedabad'),
('Myra Yadav', 'Motorcycle', null, 'Lucknow'),
('Advik Chauhan', 'Car', 4, 'Surat'),
('Aadya Rana', 'Scooter', 1, 'Kanpur'),
('Shaurya Gupta', 'Car', 2, 'Nagpur'),
('Avni Mishra', 'Motorcycle', 1, 'Indore'),
('Reyansh Tiwari', 'Car', 1, 'Thane'),
('Kiara Pandey', 'Scooter', 2, 'Bhopal'),
('Veer Singh', 'Car', 3, null),
('Anika Sharma', 'Motorcycle', 1, 'Pimpri-Chinchwad'),
('Arnav Patel', 'Car', 2, 'Patna'),
('Navya Kumar', 'Scooter', 1, 'Vadodara'),
('Dhruv Reddy', 'Car', 1, 'Ghaziabad'),
('Prisha Joshi', 'Motorcycle', 2, null),
('Tanay Mehta', 'Car', 4, 'Agra'),
('Riya Desai', 'Scooter', 1, 'Nashik'),
('Ishaan Verma', 'Car', 2, 'Faridabad'),
('Anvi Yadav', 'Motorcycle', null, 'Meerut'),
('Kiaan Chauhan', 'Car', 1, 'Rajkot'),
('Aarohi Rana', 'Scooter', 2, 'Kalyan-Dombivli'),
('Vihaan Gupta', 'Car', 3, 'Vasai-Virar'),
('Sara Mishra', 'Motorcycle', 1, 'Varanasi'),
('Neil Tiwari', 'Car', 2, 'Srinagar'),
('Shanaya Pandey', 'Scooter', 1, 'Aurangabad'),
('Atharva Singh', 'Car', 1, 'Dhanbad'),
('Aarna Sharma', 'Motorcycle', 2, 'Amritsar'),
('Yash Patel', 'Car', 4, 'Navi Mumbai'),
('Samaira Kumar', 'Scooter', 1, 'Allahabad'),
('Ayush Reddy', 'Car', 2, 'Ranchi'),
('Aanya Joshi', 'Motorcycle', 1, 'Howrah'),
('Dev Mehta', 'Car', 1, 'Coimbatore'),
('Pari Desai', 'Scooter', 2, 'Jabalpur'),
('Om Verma', 'Car', 3, 'Gwalior'),
('Meera Yadav', 'Motorcycle', 1, 'Vijayawada')

select * from vehicle_survey