create table StudentGames (
StudentID serial primary key,
StudentName varchar,
Class int,
GamePlayed varchar,
HoursPlayed DECIMAL(4, 2)
)

insert into StudentGames (StudentName, Class, GamePlayed, HoursPlayed) values
('Alice Smith', 8, 'Chess', 2.50),
('Bob Johnson', 9, 'Basketball', 3.00),
('Charlie Brown', 7, 'Football', 1.75),
('David Lee', 10, 'Tennis', 2.00),
('Eve Wilson', 8, null, 1.50),
('Frank Garcia', 9, 'Cricket', 4.00),
('Grace Rodriguez', 7, 'Volleyball', 2.25),
('Henry Martinez', 10, 'Table Tennis', 1.00),
('Ivy Anderson', null, 'Swimming', 2.75),
('Jack Thomas', 9, 'Hockey', 3.50),
('Kelly Jackson', 7, 'Carrom', 1.25),
('Liam White', 10, 'Athletics', 2.50),
('Mia Harris', 8, 'Kabaddi', 3.00),
('Noah Martin', 9, 'Kho Kho', 1.75),
('Olivia Thompson', 7, 'Chess', 2.00),
('Peter Garcia',null, null, 1.50),
('Quinn Martinez', 8, 'Football', 4.00),
('Ryan Anderson', 9, 'Tennis', 2.25),
('Sophia Thomas', 7, 'Badminton', 1.00),
('Tyler Jackson', 10, 'Cricket', 2.75),
('Ursula White', 8, 'Volleyball', 3.50),
('Victor Harris', 9, 'Table Tennis', 1.25),
('Wendy Martin', 7, 'Swimming', 2.50),
('Xavier Thompson', 10, null, 3.00),
('Yara Garcia', 8, 'Carrom', 1.75),
('Zachary Martinez', 9, 'Athletics', 2.00),
('Arya Sharma', 7, 'Chess', 1.50),
('Ishaan Kumar', 10, 'Basketball', 4.00),
('Neha Singh', null, 'Football', 2.25),
('Rohan Patel', 9, 'Tennis', 1.00),
('Sanya Joshi', 7, 'Badminton', 2.75),
('Veer Reddy', 10, 'Cricket', 3.50),
('Diya Menon', 8, 'Volleyball', 1.25),
('Arnav Nair', 9, 'Table Tennis', 2.50),
('Siya Pillai', 7, 'Swimming', 3.00),
('Kabir Iyer', 10, 'Hockey', 1.75),
('Ananya Rao', 8, 'Carrom', 2.00),
('Vivaan Desai', 9, 'Athletics', 1.50),
('Aditi Mehta', 7, 'Kabaddi', 4.00),
('Advik Kapoor', 10, 'Kho Kho', 2.25),
('Aarav Khanna', 8, 'Chess', 1.00)

select * from StudentGames